/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ScoardField.java
 *
 * Created on Jan 28, 2012, 5:51:32 PM
 */
package ScoardUI;

/**
 *
 * @author j0ni
 */
public class ScoardField extends javax.swing.JFrame {

    /** Creates new form ScoardField */
    public ScoardField() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        teamlbl1 = new javax.swing.JLabel();
        teamlbl2 = new javax.swing.JLabel();
        teamscore1 = new javax.swing.JTextField();
        teamscore2 = new javax.swing.JTextField();
        hitsPanel = new javax.swing.JPanel();
        fshoot = new javax.swing.JTextField();
        sshoot = new javax.swing.JTextField();
        tshoot = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tareaNotes = new javax.swing.JTextArea();
        radiox2r2 = new javax.swing.JRadioButton();
        radiox2r1 = new javax.swing.JRadioButton();
        radiox2r3 = new javax.swing.JRadioButton();
        radiox3r1 = new javax.swing.JRadioButton();
        radiox3r2 = new javax.swing.JRadioButton();
        radiox3r3 = new javax.swing.JRadioButton();
        lblscore = new javax.swing.JLabel();
        isTurn1 = new javax.swing.JRadioButton();
        isTurn2 = new javax.swing.JRadioButton();
        helpbar = new javax.swing.JLabel();
        resetbtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        scoardMenu = new javax.swing.JMenuBar();
        menu_file = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        menu_help = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 0));
        setForeground(new java.awt.Color(153, 204, 0));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Score Board");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 0), new java.awt.Color(255, 0, 0), null, null));

        teamlbl1.setText("Player 1:");

        teamlbl2.setText("Player 2:");

        teamscore1.setEditable(false);
        teamscore1.setText("501");
        teamscore1.setAutoscrolls(false);
        teamscore1.setPreferredSize(new java.awt.Dimension(30, 19));

        teamscore2.setEditable(false);
        teamscore2.setText("501");
        teamscore2.setAutoscrolls(false);

        hitsPanel.setBackground(new java.awt.Color(204, 255, 153));
        hitsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Round Hits"));

        fshoot.setText("first shoot");

        sshoot.setText("second shoot");

        tshoot.setText("third shoot");

        tareaNotes.setColumns(20);
        tareaNotes.setRows(5);
        jScrollPane1.setViewportView(tareaNotes);

        radiox2r2.setText("x2");

        radiox2r1.setText("x2");

        radiox2r3.setText("x2");

        radiox3r1.setText("x3");

        radiox3r2.setText("x3");

        radiox3r3.setText("x3");

        lblscore.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblscore.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblscore.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 153, 51), new java.awt.Color(0, 102, 51), null));

        javax.swing.GroupLayout hitsPanelLayout = new javax.swing.GroupLayout(hitsPanel);
        hitsPanel.setLayout(hitsPanelLayout);
        hitsPanelLayout.setHorizontalGroup(
            hitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hitsPanelLayout.createSequentialGroup()
                .addGroup(hitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hitsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(hitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sshoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fshoot, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tshoot, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(hitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(hitsPanelLayout.createSequentialGroup()
                                .addComponent(radiox2r1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radiox3r1))
                            .addGroup(hitsPanelLayout.createSequentialGroup()
                                .addComponent(radiox2r2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radiox3r2))
                            .addGroup(hitsPanelLayout.createSequentialGroup()
                                .addComponent(radiox2r3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radiox3r3))))
                    .addGroup(hitsPanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lblscore, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        hitsPanelLayout.setVerticalGroup(
            hitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hitsPanelLayout.createSequentialGroup()
                .addGroup(hitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hitsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                    .addGroup(hitsPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(hitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(hitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(radiox2r1)
                                .addComponent(radiox3r1))
                            .addComponent(fshoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(hitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(hitsPanelLayout.createSequentialGroup()
                                .addComponent(sshoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addGroup(hitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tshoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(radiox2r3)
                                    .addComponent(radiox3r3)))
                            .addGroup(hitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(radiox2r2)
                                .addComponent(radiox3r2)))
                        .addGap(18, 18, 18)
                        .addComponent(lblscore, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)))
                .addContainerGap())
        );

        isTurn1.setLabel("");
        isTurn1.setName("jradio1"); // NOI18N

        isTurn2.setLabel("");
        isTurn2.setName("jradio2"); // NOI18N

        helpbar.setBackground(new java.awt.Color(153, 204, 0));
        helpbar.setForeground(new java.awt.Color(102, 255, 102));
        helpbar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        helpbar.setFocusable(false);
        helpbar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        helpbar.setName("lblnotes"); // NOI18N

        resetbtn.setText("Reset");
        resetbtn.setActionCommand("resetbtn");

        exitbtn.setText("Finish");
        exitbtn.setActionCommand("exitbtn");

        menu_file.setText("File");

        jMenu5.setText("jMenu5");
        menu_file.add(jMenu5);

        scoardMenu.add(menu_file);

        menu_help.setText("help");
        scoardMenu.add(menu_help);

        setJMenuBar(scoardMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(helpbar, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(resetbtn)
                            .addGap(18, 18, 18)
                            .addComponent(exitbtn)
                            .addGap(99, 99, 99))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(teamlbl1)
                                .addComponent(teamlbl2))
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(teamscore2)
                                .addComponent(teamscore1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(isTurn1)
                                .addComponent(isTurn2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(hitsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addContainerGap()))))
            .addGroup(layout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addComponent(jLabel1)
                .addContainerGap(403, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hitsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(resetbtn)
                            .addComponent(exitbtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(teamlbl1)
                            .addComponent(teamscore1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(isTurn1))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(teamlbl2)
                            .addComponent(teamscore2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(isTurn2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(helpbar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoardField.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoardField.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoardField.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoardField.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ScoardField().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton exitbtn;
    private javax.swing.JTextField fshoot;
    private javax.swing.JLabel helpbar;
    private javax.swing.JPanel hitsPanel;
    private javax.swing.JRadioButton isTurn1;
    private javax.swing.JRadioButton isTurn2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblscore;
    private javax.swing.JMenu menu_file;
    private javax.swing.JMenu menu_help;
    private javax.swing.JRadioButton radiox2r1;
    private javax.swing.JRadioButton radiox2r2;
    private javax.swing.JRadioButton radiox2r3;
    private javax.swing.JRadioButton radiox3r1;
    private javax.swing.JRadioButton radiox3r2;
    private javax.swing.JRadioButton radiox3r3;
    private javax.swing.JButton resetbtn;
    private javax.swing.JMenuBar scoardMenu;
    private javax.swing.JTextField sshoot;
    private javax.swing.JTextArea tareaNotes;
    private javax.swing.JLabel teamlbl1;
    private javax.swing.JLabel teamlbl2;
    private javax.swing.JTextField teamscore1;
    private javax.swing.JTextField teamscore2;
    private javax.swing.JTextField tshoot;
    // End of variables declaration//GEN-END:variables
}
